### ISSUE TITLE
Use `json-ts-mode`

### ISSUE THREAD

**Issue by zetashift** [JasZhe/hurl-mode#5]
Since `json-ts-mode` is a built in mode from Emacs v30+ onwards, is it possible to use that for font locking instead?

**Comment by JasZhe** [comment]
hey sorry it took a while but it should be working now in this commit: [a0bd4a76173296df0afc60801ff3e0ade19634ae](https://github.com/JasZhe/hurl-mode/commit/a0bd4a76173296df0afc60801ff3e0ade19634ae) try it out and let me know if there's any problems

**Comment by zetashift** [comment]
Hi! Thank you for this!!

When I do `hurl-mode` I still get the following by the way:

```
load-with-code-conversion: Cannot open load file: No such file or directory, json-mode
```

**Comment by JasZhe** [comment]
Oh I see.. that's a mistake on my part, for some reason I thought json-mode was part of core emacs. I'll see if I can make that part more optional

**Comment by JasZhe** [comment]
I pushed a fix just now to make json-mode an optional dependency so see if that fixes it for you thanks!
